#!/usr/bin/env bash

set -ex

cd /autograder/source

MAIN_BRANCH=$(git remote show origin | sed -n '/HEAD branch/s/.*: //p')

git pull origin $MAIN_BRANCH

# The following line is needed for this reason:
# we have just pulled a new version of the course project,
# which has the autograder as a dependency.
# If we update the version of the autograder in that project,
# `run_autograder_main` may change.
# So we need to make sure that the latest versions of the dependencies are present
# before we copy that file over.

~/.elan/bin/lake update

cp lake-packages/autograder/run_autograder_main .

./run_autograder_main